"""Build docs/static/data/hero_plans.js: the plans OntoPlan returned for the Klickitat Small tasks.

The hero graph on the project page shows each task's goal entities and then plays the plan
OntoPlan produced for it. Only tasks whose plan reached Task Success are included.

    python docs/scripts/build_hero_plans.py --results experiments/results/final/full/general
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "docs/static/data/hero_plans.js"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--results", type=Path, required=True, help="result files of experiments/run.py (full system)")
    args = ap.parse_args()
    plans = {}
    for path in sorted(args.results.glob("Klickitat_small_S*.json")):
        record = json.loads(path.read_text())
        if not record["score"]["task_success"]:
            continue
        task_id = record["task"]["id"]
        plans[task_id] = [action.strip().strip("()").split() for action in record["plan"]]
    OUT.write_text("/* Generated by docs/scripts/build_hero_plans.py: OntoPlan's plans for the Klickitat Small tasks. */\n"
                   "window.ONTOPLAN_HERO_PLANS = " + json.dumps(plans, separators=(",", ":")) + ";\n")
    print(OUT, len(plans), "plans")


if __name__ == "__main__":
    main()
